### ISSUE TITLE
The TreeView icon is a little larger than other icons

### ISSUE THREAD

**Issue by pavsaund** [dolittle-tools/vscode#13]
More visual feedback, the Dolittle icon is a little too large compared to other icons. It looks out of place. Is it possible to decrease it to the same size?

<img width="53" alt="image" src="https://user-images.githubusercontent.com/102054/51097139-1e3e3b80-17c2-11e9-93f6-23ceb1d960ae.png">

**Comment by Virrum** [comment]
A PR is coming your way

**Comment by Virrum** [comment]
PR #14
